name: Run tests

on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: "16"

      - run: npm ci
      - run: npm run lint
      - run: npm test
